
services:
  db:
    container_name: postgres_db
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    # given: healthcheck
    # basically just checks that postgres is up and ready
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    # In case you were wondering, 
    # since we aren't specifying an image for app, we're telling it 
    # to look in the current directory for the build (from Dockerfile)
    build: .
    container_name: go_app
    # if our DB is not healthy
    # do not run
    depends_on:
      db:
        condition: service_healthy
    #TODO:
      # define environment variables
      # (DB_HOST (the name of the service our db is in)
      #, DB_PORT, DB_USER, DB_PASSWORD, DB_NAME, 
      # and (this container's) PORT 8080)
    ports:
          - "8080:8080"
    environment:
        DB_HOST: db
        DB_PORT: 5432
        DB_USER: user
        DB_PASSWORD: password
        DB_NAME: mydb

volumes:
  pgdata: